In [1]:
import pandas as pd 
import numpy as np
import matplotlib
%matplotlib inline
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import random
import warnings
warnings.filterwarnings('ignore')
import os

In [2]:
os.chdir('<filepath>')

In [3]:
data = pd.read_csv('pacific.csv')
display(data)

ID                 Name      Date  Time Event Status Latitude  \
0      EP011949              UNNAMED  19490611     0           TS    20.2N   
1      EP011949              UNNAMED  19490611   600           TS    20.2N   
2      EP011949              UNNAMED  19490611  1200           TS    20.2N   
3      EP011949              UNNAMED  19490611  1800           TS    20.3N   
4      EP011949              UNNAMED  19490612     0           TS    20.4N   
...         ...                  ...       ...   ...   ...    ...      ...   
26132  EP222015               SANDRA  20151128  1200           LO    21.7N   
26133  EP222015               SANDRA  20151128  1800           LO    22.4N   
26134  EP222015               SANDRA  20151129     0           LO    23.1N   
26135  EP222015               SANDRA  20151129   600           LO    23.5N   
26136  EP222015               SANDRA  20151129  1200           LO    24.2N   

      Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  \
0        106.3W            45              -999  ...         -999   
1        106.4W            45              -999  ...         -999   
2        106.7W            45              -999  ...         -999   
3        107.7W            45              -999  ...         -999   
4        108.6W            45              -999  ...         -999   
...         ...           ...               ...  ...          ...   
26132    109.0W            35              1002  ...            0   
26133    108.7W            30              1007  ...            0   
26134    108.3W            30              1008  ...            0   
26135    107.9W            25              1009  ...            0   
26136    107.7W            20              1010  ...            0   

       Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  \
0             -999              -999              -999              -999   
1             -999              -999              -999              -999   
2             -999              -999              -999              -999   
3             -999              -999              -999              -999   
4             -999              -999              -999              -999   
...            ...               ...               ...               ...   
26132            0                 0                 0                 0   
26133            0                 0                 0                 0   
26134            0                 0                 0                 0   
26135            0                 0                 0                 0   
26136            0                 0                 0                 0   

       Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  \
0                  -999          -999          -999          -999   
1                  -999          -999          -999          -999   
2                  -999          -999          -999          -999   
3                  -999          -999          -999          -999   
4                  -999          -999          -999          -999   
...                 ...           ...           ...           ...   
26132                 0             0             0             0   
26133                 0             0             0             0   
26134                 0             0             0             0   
26135                 0             0             0             0   
26136                 0             0             0             0   

       High Wind NW  
0              -999  
1              -999  
2              -999  
3              -999  
4              -999  
...             ...  
26132             0  
26133             0  
26134             0  
26135             0  
26136             0  

[26137 rows x 22 columns]

In [6]:
print(data.groupby('Status').agg({'Status':np.size}))

        Status
Status        
 DB        217
 ET        152
 EX        110
 HU       6766
 LO       1828
 PT          6
 SD          4
 SS          7
 ST          6
 TD       6965
 TS      10076


In [7]:
data.Status = pd.Categorical(data.Status)
data['Status'] = data.Status.cat.codes
display(data.head())

ID                 Name      Date  Time Event  Status Latitude  \
0  EP011949              UNNAMED  19490611     0            10    20.2N   
1  EP011949              UNNAMED  19490611   600            10    20.2N   
2  EP011949              UNNAMED  19490611  1200            10    20.2N   
3  EP011949              UNNAMED  19490611  1800            10    20.3N   
4  EP011949              UNNAMED  19490612     0            10    20.4N   

  Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  \
0    106.3W            45              -999  ...         -999         -999   
1    106.4W            45              -999  ...         -999         -999   
2    106.7W            45              -999  ...         -999         -999   
3    107.7W            45              -999  ...         -999         -999   
4    108.6W            45              -999  ...         -999         -999   

   Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  \
0              -999              -999              -999              -999   
1              -999              -999              -999              -999   
2              -999              -999              -999              -999   
3              -999              -999              -999              -999   
4              -999              -999              -999              -999   

   High Wind NE  High Wind SE  High Wind SW  High Wind NW  
0          -999          -999          -999          -999  
1          -999          -999          -999          -999  
2          -999          -999          -999          -999  
3          -999          -999          -999          -999  
4          -999          -999          -999          -999  

[5 rows x 22 columns]

In [9]:
print(data.groupby('Status').agg({'Status':np.size}))
#status column has been label encoded

        Status
Status        
0          217
1          152
2          110
3         6766
4         1828
5            6
6            4
7            7
8            6
9         6965
10       10076


In [10]:
#removing unnecessary columns
pred_columns = data[:]
pred_columns.drop(['Status'],axis=1,inplace=True)
pred_columns.drop(['Event'],axis=1,inplace=True)
pred_columns.drop(['Latitude'],axis=1,inplace=True)
pred_columns.drop(['Longitude'],axis=1,inplace=True)
pred_columns.drop(['ID'],axis=1,inplace=True)
pred_columns.drop(['Name'],axis=1,inplace=True)
pred_columns.drop(['Date'],axis=1,inplace=True)
pred_columns.drop(['Time'],axis=1,inplace=True)
display((pred_columns))

Maximum Wind  Minimum Pressure  Low Wind NE  Low Wind SE  Low Wind SW  \
0                45              -999         -999         -999         -999   
1                45              -999         -999         -999         -999   
2                45              -999         -999         -999         -999   
3                45              -999         -999         -999         -999   
4                45              -999         -999         -999         -999   
...             ...               ...          ...          ...          ...   
26132            35              1002           60            0            0   
26133            30              1007            0            0            0   
26134            30              1008            0            0            0   
26135            25              1009            0            0            0   
26136            20              1010            0            0            0   

       Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  \
0             -999              -999              -999              -999   
1             -999              -999              -999              -999   
2             -999              -999              -999              -999   
3             -999              -999              -999              -999   
4             -999              -999              -999              -999   
...            ...               ...               ...               ...   
26132            0                 0                 0                 0   
26133            0                 0                 0                 0   
26134            0                 0                 0                 0   
26135            0                 0                 0                 0   
26136            0                 0                 0                 0   

       Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  \
0                  -999          -999          -999          -999   
1                  -999          -999          -999          -999   
2                  -999          -999          -999          -999   
3                  -999          -999          -999          -999   
4                  -999          -999          -999          -999   
...                 ...           ...           ...           ...   
26132                 0             0             0             0   
26133                 0             0             0             0   
26134                 0             0             0             0   
26135                 0             0             0             0   
26136                 0             0             0             0   

       High Wind NW  
0              -999  
1              -999  
2              -999  
3              -999  
4              -999  
...             ...  
26132             0  
26133             0  
26134             0  
26135             0  
26136             0  

[26137 rows x 14 columns]

In [11]:
x = pred_columns.values
display (x)

array([[  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       [  45, -999, -999, ..., -999, -999, -999],
       ...,
       [  30, 1008,    0, ...,    0,    0,    0],
       [  25, 1009,    0, ...,    0,    0,    0],
       [  20, 1010,    0, ...,    0,    0,    0]])

In [12]:
y =data['Status'].values
print (y)

[10 10 10 ...  4  4  4]


In [13]:
from sklearn.model_selection  import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)
print (x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26137, 14)
(18295, 14)
(7842, 14)
(18295,)
(7842,)


In [14]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
log_pred = logmodel.predict(x)
print (log_pred)
print (pd.DataFrame(log_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,log_pred))
print('\nClassification Report')
print(classification_report (y,log_pred))
print('Confusion Matrix')
print (confusion_matrix (y,log_pred))

[10 10 10 ...  4  4  4]
        0
0        
3    6734
4    3020
9    5570
10  10813

 Accuracy Score
0.7657343995102728

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.87      0.86      0.86      6766
           4       0.55      0.91      0.69      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.77      0.62      0.69      6965
          10       0.76      0.82      0.79     10076

    accuracy                           0.77     26137
   macro avg       0.27      0.29      0.27     26137
weighted avg       0.76      0.77      0.76     26137

Confusion Matrix
[[   0    0    0    0  217 

In [15]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 2)
KNN1.fit(x_train,y_train)
KNN1_pred = KNN1.predict(x)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN1_pred))
print('\nClassification Report')
print(classification_report (y,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN1_pred))

[10 10 10 ...  9  4  4]
        0
0        
3    6807
4    1966
9    7225
10  10139

 Accuracy Score
0.9509124995217507

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      0.99      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.93      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [16]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =5 , metric = 'minkowski', p= 2)
KNN1.fit(x_train,y_train)
KNN1_pred = KNN1.predict(x)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN1_pred))
print('\nClassification Report')
print(classification_report (y,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN1_pred))

[10 10 10 ...  9  4  4]
        0
0        
0     157
2      18
3    6775
4    1762
8       5
9    7236
10  10184

 Accuracy Score
0.9459004476412748

Classification Report
              precision    recall  f1-score   support

           0       0.25      0.18      0.21       217
           1       0.00      0.00      0.00       152
           2       0.67      0.11      0.19       110
           3       1.00      1.00      1.00      6766
           4       0.71      0.68      0.70      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.80      0.67      0.73         6
           9       0.91      0.95      0.93      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.48      0.42      0.43     26137
weighted avg       0.94      0.95      0.94     26137

Confusion Matr

In [17]:
KNN1_pred = KNN1.predict(x_test)
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (y_test,KNN1_pred))
print('\nClassification Report')
print(classification_report (y_test,KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (y_test,KNN1_pred))

[ 9  3 10 ...  3 10 10]
       0
0       
0     57
2      5
3   2012
4    562
9   2156
10  3050

 Accuracy Score
0.9415965314970671

Classification Report
              precision    recall  f1-score   support

           0       0.21      0.16      0.18        74
           1       0.00      0.00      0.00        46
           2       0.80      0.10      0.18        39
           3       1.00      1.00      1.00      2014
           4       0.68      0.69      0.69       558
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         2
           9       0.91      0.94      0.93      2092
          10       0.99      1.00      0.99      3013

    accuracy                           0.94      7842
   macro avg       0.46      0.39      0.40      7842
weighted avg       0.93      0.94      0.94      7842

Confusion Matrix
[[  12    0    0    0   61    0    0    0    1    0]
 [   0    0    0

In [18]:
from sklearn.neighbors import KNeighborsClassifier
KNN2 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 1)
KNN2.fit(x_train,y_train)
KNN2_pred = KNN2.predict(x)
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,KNN2_pred))
print('\nClassification Report')
print(classification_report (y,KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (y,KNN2_pred))

[10 10 10 ...  9  4  4]
        0
0        
3    6772
4    1956
9    7252
10  10157

 Accuracy Score
0.9520220377242989

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.93      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [19]:
KNN2_pred = KNN2.predict(x_test)
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y_test,KNN2_pred))
print('\nClassification Report')
print(classification_report (y_test,KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (y_test,KNN2_pred))

[ 9  3 10 ...  3 10 10]
       0
0       
3   2018
4    610
9   2179
10  3035

 Accuracy Score
0.9506503442999235

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        74
           1       0.00      0.00      0.00        46
           2       0.00      0.00      0.00        39
           3       0.99      1.00      1.00      2014
           4       0.73      0.80      0.76       558
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         2
           9       0.92      0.96      0.94      2092
          10       0.99      1.00      0.99      3013

    accuracy                           0.95      7842
   macro avg       0.36      0.37      0.37      7842
weighted avg       0.93      0.95      0.94      7842

Confusion Matrix
[[   0    0    0    0   74    0    0    0    0    0]
 [   0    0    0    2    0    0   

In [20]:
from sklearn.naive_bayes import GaussianNB
GNB= GaussianNB()
GNB.fit(x_train,y_train)
GNB_pred = GNB.predict(x)
print (GNB_pred)
print (pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,GNB_pred))
print('\nClassification Report')
print(classification_report (y,GNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,GNB_pred))

[1 1 1 ... 0 0 0]
        0
0        
0    2714
1   19750
3    1090
4       6
5     234
6     304
7    1869
8     163
10      7

 Accuracy Score
0.05666296820599151

Classification Report
              precision    recall  f1-score   support

           0       0.08      0.99      0.15       217
           1       0.01      1.00      0.02       152
           2       0.00      0.00      0.00       110
           3       1.00      0.16      0.28      6766
           4       0.00      0.00      0.00      1828
           5       0.01      0.33      0.02         6
           6       0.01      1.00      0.03         4
           7       0.00      1.00      0.01         7
           8       0.04      1.00      0.07         6
           9       0.00      0.00      0.00      6965
          10       1.00      0.00      0.00     10076

    accuracy                           0.06     26137
   macro avg       0.20      0.50      0.05     26137
weighted avg       0.64      0.06      0.07     26137


In [21]:
from sklearn.naive_bayes import GaussianNB
GNB= GaussianNB()
GNB.fit(x_train,y_train)
GNB_pred = GNB.predict(x)
print (GNB_pred)
print (pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,GNB_pred))
print('\nClassification Report')
print(classification_report (y,GNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,GNB_pred))

[1 1 1 ... 0 0 0]
        0
0        
0    2714
1   19750
3    1090
4       6
5     234
6     304
7    1869
8     163
10      7

 Accuracy Score
0.05666296820599151

Classification Report
              precision    recall  f1-score   support

           0       0.08      0.99      0.15       217
           1       0.01      1.00      0.02       152
           2       0.00      0.00      0.00       110
           3       1.00      0.16      0.28      6766
           4       0.00      0.00      0.00      1828
           5       0.01      0.33      0.02         6
           6       0.01      1.00      0.03         4
           7       0.00      1.00      0.01         7
           8       0.04      1.00      0.07         6
           9       0.00      0.00      0.00      6965
          10       1.00      0.00      0.00     10076

    accuracy                           0.06     26137
   macro avg       0.20      0.50      0.05     26137
weighted avg       0.64      0.06      0.07     26137


In [22]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(x_train,y_train)
BNB_pred = BNB.predict(x)
print (BNB_pred)
print (pd.DataFrame(BNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,BNB_pred))
print('\nClassification Report')
print(classification_report (y,BNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,BNB_pred))	

[9 9 9 ... 9 9 9]
        0
0        
3      20
7     660
8    1235
9   22770
10   1452

 Accuracy Score
0.32046524084630984

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.05      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.29      0.01         7
           8       0.00      1.00      0.01         6
           9       0.31      1.00      0.47      6965
          10       0.97      0.14      0.24     10076

    accuracy                           0.32     26137
   macro avg       0.12      0.22      0.07     26137
weighted avg       0.47      0.32      0.22     26137

Confusion Matrix
[[   0    0    0    0 

In [23]:
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(x_train,y_train)
BNB_pred = BNB.predict(x)
print (BNB_pred)
print (pd.DataFrame(BNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,BNB_pred))
print('\nClassification Report')
print(classification_report (y,BNB_pred))
print('Confusion Matrix')
print (confusion_matrix (y,BNB_pred))	

[9 9 9 ... 9 9 9]
        0
0        
3      20
7     660
8    1235
9   22770
10   1452

 Accuracy Score
0.32046524084630984

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.05      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.29      0.01         7
           8       0.00      1.00      0.01         6
           9       0.31      1.00      0.47      6965
          10       0.97      0.14      0.24     10076

    accuracy                           0.32     26137
   macro avg       0.12      0.22      0.07     26137
weighted avg       0.47      0.32      0.22     26137

Confusion Matrix
[[   0    0    0    0 

In [25]:
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'sigmoid')
SVM_SIG.fit(x_train,y_train)
SVM_SIG_pred = SVM_SIG.predict(x)
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (y,SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_SIG_pred))

[10 10 10 ...  3  3  3]
        0
0        
3    4346
4    2041
9    6946
10  12804

 Accuracy Score
0.2898190304931706

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.00      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.31      0.31      0.31      6965
          10       0.42      0.54      0.47     10076

    accuracy                           0.29     26137
   macro avg       0.07      0.08      0.07     26137
weighted avg       0.25      0.29      0.27     26137

Confusion Matrix
[[   0    0    0  217    0 

In [26]:
from sklearn.svm import SVC
SVM_POLY = SVC (kernel = 'poly')
SVM_POLY.fit(x_train,y_train)
SVM_POLY_pred = SVM_POLY.predict(x)
print (SVM_POLY_pred)
print (pd.DataFrame(SVM_POLY_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_POLY_pred))
print('\nClassification Report')
print(classification_report (y,SVM_POLY_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_POLY_pred))

[10 10 10 ... 10 10 10]
        0
0        
3    5642
9    6615
10  13880

 Accuracy Score
0.8064429735623828

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.83      0.91      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.88      0.84      0.86      6965
          10       0.69      0.95      0.80     10076

    accuracy                           0.81     26137
   macro avg       0.23      0.24      0.23     26137
weighted avg       0.76      0.81      0.77     26137

Confusion Matrix
[[   0    0    0    0    0    0    0 

In [27]:
from sklearn.svm import SVC
SVM_LIN = SVC (kernel = 'linear')
SVM_LIN.fit(x_train,y_train)
SVM_LIN_pred = SVM_LIN.predict(x)
print (SVM_LIN_pred)
print (pd.DataFrame(SVM_LIN_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_LIN_pred))
print('\nClassification Report')
print(classification_report (y,SVM_LIN_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_LIN_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       1
3    6784
4    1993
8       6
9    7179
10  10174

 Accuracy Score
0.9555419520220377

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.80      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.67      0.67      0.67         6
           9       0.93      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.96     26137
   macro avg       0.39      0.40      0.40     26137
weighted avg       0.94      0.96      0.95     26137

Confusion Matrix
[[    0

In [28]:
from sklearn.svm import SVC
SVM_RBF = SVC (kernel = 'rbf')
SVM_RBF.fit(x_train,y_train)
SVM_RBF_pred = SVM_RBF.predict(x)
print (SVM_RBF_pred)
print (pd.DataFrame(SVM_RBF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,SVM_RBF_pred))
print('\nClassification Report')
print(classification_report (y,SVM_RBF_pred))
print('Confusion Matrix')
print (confusion_matrix (y,SVM_RBF_pred))

[10 10 10 ...  4  4  4]
        0
0        
3    5324
4    3262
10  17551

 Accuracy Score
0.6404713624363928

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.78      0.87      6766
           4       0.51      0.92      0.66      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.56      0.97      0.71     10076

    accuracy                           0.64     26137
   macro avg       0.19      0.24      0.20     26137
weighted avg       0.51      0.64      0.54     26137

Confusion Matrix
[[   0    0    0    0  217    0    0 

In [29]:
from sklearn.tree import DecisionTreeClassifier
TREE = DecisionTreeClassifier (criterion = 'entropy')
TREE.fit(x_train,y_train)
TREE_pred = TREE.predict(x)
print (TREE_pred)
print (pd.DataFrame(TREE_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,TREE_pred))
print('\nClassification Report')
print(classification_report (y,TREE_pred))
print('Confusion Matrix')
print (confusion_matrix (y,TREE_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       9
2      21
3    6784
4    2095
5       3
7       8
8       6
9    7098
10  10113

 Accuracy Score
0.9585262271875119

Classification Report
              precision    recall  f1-score   support

           0       0.44      0.02      0.04       217
           1       0.00      0.00      0.00       152
           2       0.90      0.17      0.29       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       0.67      0.33      0.44         6
           6       0.00      0.00      0.00         4
           7       0.75      0.86      0.80         7
           8       1.00      1.00      1.00         6
           9       0.94      0.95      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.68      0.56      0.57     26137
weighted avg       0.95      0.96      0.95     2

In [30]:
from sklearn.tree import DecisionTreeClassifier
TREE_GINI = DecisionTreeClassifier (criterion = 'gini')
TREE_GINI.fit(x_train,y_train)
TREE_GINI_pred = TREE_GINI.predict(x)
print (TREE_GINI_pred)
print (pd.DataFrame(TREE_GINI_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,TREE_GINI_pred))
print('\nClassification Report')
print(classification_report (y,TREE_GINI_pred))
print('Confusion Matrix')
print (confusion_matrix (y,TREE_GINI_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       9
2      20
3    6784
4    2092
5       3
7       8
8       6
9    7096
10  10119

 Accuracy Score
0.9587557868156253

Classification Report
              precision    recall  f1-score   support

           0       0.44      0.02      0.04       217
           1       0.00      0.00      0.00       152
           2       0.95      0.17      0.29       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       0.67      0.33      0.44         6
           6       0.00      0.00      0.00         4
           7       0.75      0.86      0.80         7
           8       1.00      1.00      1.00         6
           9       0.94      0.95      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.68      0.56      0.57     26137
weighted avg       0.95      0.96      0.95     2

In [31]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='entropy')
RF.fit(x_train,y_train)
RF_pred = RF.predict(x)
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,RF_pred))
print('\nClassification Report')
print(classification_report (y,RF_pred))
print('Confusion Matrix')
print (confusion_matrix (y,RF_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       4
2      21
3    6784
4    2072
5       2
7       8
8       6
9    7109
10  10131

 Accuracy Score
0.9592149060718521

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.02       217
           1       0.00      0.00      0.00       152
           2       0.90      0.17      0.29       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.75      0.86      0.80         7
           8       1.00      1.00      1.00         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.71      0.56      0.58     26137
weighted avg       0.95      0.96      0.95     2

In [32]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='gini')
RF.fit(x_train,y_train)
RF_pred = RF.predict(x)
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (y,RF_pred))
print('\nClassification Report')
print(classification_report (y,RF_pred))
print('Confusion Matrix')
print (confusion_matrix (y,RF_pred))

[10 10 10 ...  9  4  4]
        0
0        
0       4
2      20
3    6784
4    2085
5       2
7       8
8       6
9    7096
10  10132

 Accuracy Score
0.9591383861958144

Classification Report
              precision    recall  f1-score   support

           0       0.50      0.01      0.02       217
           1       0.00      0.00      0.00       152
           2       0.95      0.17      0.29       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.75      0.86      0.80         7
           8       1.00      1.00      1.00         6
           9       0.94      0.95      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.72      0.56      0.58     26137
weighted avg       0.95      0.96      0.95     2