In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [35]:
os.chdir('<filepath>')

In [36]:
df1 = pd.read_excel('Data Preprocessing Data File.xlsx')
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [37]:
x = df1.iloc[:,:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [38]:
x = df1.iloc[:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [39]:
y = df1.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [40]:
x[:,1:2] #this has the missing datatypes

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [41]:
#filling in the missing data in a file
from sklearn.impute import SimpleImputer #sklearn is widely used to fill missing data, used to create ML algorithms
si = SimpleImputer() #creates an instance of the sklearn class. This will be used to fill in missing data
si.fit(x[:,1:2]) #this line is going to take the average of the given data in the specified column which is column 2 of 'x' here
si.transform(x[:,1:2]) #the .transform makes the changes by imputing the data calcualted in the previos .fit step and fills in empty data

array([[44.   ],
       [27.   ],
       [39.875],
       [39.   ],
       [39.875],
       [35.   ],
       [39.   ],
       [48.   ],
       [50.   ],
       [37.   ]])

In [42]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'median') #by default average is taken. The strategy = 'mean' gives the median value to be filled in instead 
si.fit(x[:,1:2])
si.transform(x[:,1:2]) 

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [43]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'most_frequent') #most frequent data being used
si.fit(x[:,1:2])
si.transform(x[:,1:2]) 

array([[44.0],
       [27.0],
       [39.0],
       [39.0],
       [39.0],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [44]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'constant') #constant is used
si.fit(x[:,1:2])
si.transform(x[:,1:2])

array([[44.0],
       [27.0],
       ['missing_value'],
       [39.0],
       ['missing_value'],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [45]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'constant',fill_value=555) #constant is used but value mentioned
si.fit(x[:,1:2])
si.transform(x[:,1:2]) 

array([[44.0],
       [27.0],
       [555],
       [39.0],
       [555],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [46]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'most_frequent') #most frequent data being used for columns like country name/date
si.fit(x[:,0:1])
si.transform(x[:,0:1]) #filled with france as it is the most frequent

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)

In [1]:
#os.getcwd()

In [48]:
df1 = pd.read_excel("Data Preprocessing Data File.xlsx")
df1

Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [49]:
#column to predict will be dependant variable
x = df1.iloc[:,:-1].values #excludes last column
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [50]:
y = df1.iloc[:,3].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [51]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [52]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
x[:,1:2] = si.fit_transform(x[:,1:2])
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [53]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
x[:,2:] = si.fit_transform(x[:,2:]) #salary gap filled with average
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', 39.875, 54000.0],
       ['Spain ', 39.0, 62250.0],
       ['Germany ', 39.875, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, 62250.0],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [54]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'most_frequent')
imputer = imputer.fit(x[:,0:1])
x[:,0:1] = imputer.transform(x[:,0:1])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [55]:
#Labeling Data
from sklearn.preprocessing import LabelEncoder
label_x = LabelEncoder()
x[:,0] = label_x.fit_transform(x[:,0])
print(x) #france getns label 0, germany gets 1 and spain gets 2

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 39.875 54000.0]
 [2 39.0 62250.0]
 [1 39.875 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [64]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
y = label_y.fit_transform(y) #column indexing is not required as y has only 1 column
print(y) #yes is marked 0, no is marked 1

[0 1 0 0 1 1 0 1 0 1]


In [57]:
#OneHotEncoder is used to convert categorical data into a format that can be used by ML algos
#ColumnTransformer is used to apply different preprocessing steps to different columns. Useful when differnt columns have different data types
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('one',OneHotEncoder(),[0])]) #ColumnTransformer(transformers = [(name, transformer, columns)])
ct.fit_transform(x) #fit_transformer makes the changes
#the bottom result has classified 0 and 1 for the 3 countried, whenever the country name matches it gets a 1 and if it dosent match is shows 0

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('one',OneHotEncoder(),[0])],remainder = 'passthrough')#default remainder is 'drop' which drops other columns
#having passthrought keeps the additional columns on which OneHotEncoder is not performed
ct.fit_transform(x)

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [65]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x)) #this stores the transformed data into 'x'. The previous code dosen't do this storing and simply prints the labeled data
print (x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 39.875 54000.0]
 [1.0 0.0 0.0 1.0 39.0 62250.0]
 [1.0 0.0 1.0 0.0 39.875 64000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 39.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 62250.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [66]:
#standardisation
from sklearn.preprocessing import StandardScaler
std_sca = StandardScaler()
x_STD = std_sca.fit_transform(x) #fit here is calculating the mean value of given data
#transform standardises the vales. Done by subtracting present value from mean and dividing by standard deviation
#standard deviation shows how spread out the data is from a mean point. Higher SD means data is more spread out from the mean while lower means that given data is closer to the mean
print(pd.DataFrame(x_STD))

     0    1         2    3         4         5
0 -1.0  1.0 -0.654654 -0.5  0.664912  1.002707
1 -1.0  1.0 -0.654654 -0.5 -2.075331 -1.465494
2  1.0 -1.0  1.527525 -0.5  0.000000 -0.848444
3  1.0 -1.0 -0.654654  2.0 -0.141042  0.000000
4  1.0 -1.0  1.527525 -0.5  0.000000  0.179973
5 -1.0  1.0 -0.654654 -0.5 -0.785805 -0.437077
6  1.0 -1.0 -0.654654  2.0 -0.141042 -1.054127
7 -1.0  1.0 -0.654654 -0.5  1.309675  0.000000
8  1.0 -1.0  1.527525 -0.5  1.632056  2.133965
9 -1.0  1.0 -0.654654 -0.5 -0.463423  0.488498


In [67]:
#min max scaler: transforms columns into a given range usually between 0 and 1
from sklearn.preprocessing import MinMaxScaler
Mn_x = MinMaxScaler()
x_NOR = Mn_x.fit_transform(x) #fit calculates the max and min values
#transform then uses those values to scale x
#scaling is done by subtracting value of min form x i.e. x-min and divided by max-min
print(pd.DataFrame(x_NOR)) #converting numpy array into a pandas dataframe with labels and printing it

     0    1    2    3         4         5
0  0.0  1.0  0.0  0.0  0.739130  0.685714
1  0.0  1.0  0.0  0.0  0.000000  0.000000
2  1.0  0.0  1.0  0.0  0.559783  0.171429
3  1.0  0.0  0.0  1.0  0.521739  0.407143
4  1.0  0.0  1.0  0.0  0.559783  0.457143
5  0.0  1.0  0.0  0.0  0.347826  0.285714
6  1.0  0.0  0.0  1.0  0.521739  0.114286
7  0.0  1.0  0.0  0.0  0.913043  0.407143
8  1.0  0.0  1.0  0.0  1.000000  1.000000
9  0.0  1.0  0.0  0.0  0.434783  0.542857


In [68]:
from sklearn.preprocessing import Normalizer
Nm_x= Normalizer()
x_NOR = Nm_x.fit_transform(x) #scales by divind each element of x by norm
print (pd.DataFrame(x_NOR))

          0         1         2         3         4    5
0  0.000000  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000000  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000019  0.000000  0.000019  0.000000  0.000738  1.0
3  0.000016  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000016  0.000000  0.000016  0.000000  0.000623  1.0
5  0.000000  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000019  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000000  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000012  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000000  0.000015  0.000000  0.000000  0.000552  1.0


In [63]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 39.875 54000.0]
 [0.0 0.0 1.0 39.0 62250.0]
 [0.0 1.0 0.0 39.875 64000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 62250.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
