In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import r2_score

In [2]:
os.chdir('<filepath?')

In [1]:
#os.getcwd()

In [4]:
df1=pd.read_csv('50_Startups.csv')
print (df1)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       

In [5]:
x = df1.iloc[:,:-1].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'California'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'New York'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'California'],
       [100671.96, 91790.61, 249744.55, 'Florida'],
       [93863.75, 127320.38, 249839.44, 'California'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79

In [6]:
y = df1.iloc[:,-1].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [7]:
from sklearn.preprocessing import LabelEncoder
Label = LabelEncoder()
x[:,3]= Label.fit_transform(x[:,3])

In [8]:
print (x)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 0]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 2]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 0]
 [100671.96 91790.61 249744.55 1]
 [93863.75 127320.38 249839.44 0]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 2]
 [86419.7 153514.11 0.0 1]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 0]
 [67532.53 105751.03 304768.73 0]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 2]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print (x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 0.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 0.0 73994.56 122782.75 3

In [10]:
print (pd.DataFrame(x))

      0    1    2          3          4          5
0   0.0  0.0  1.0   165349.2   136897.8   471784.1
1   1.0  0.0  0.0   162597.7  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0   131876.9   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  0.0  1.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  0.0  101913.08  110594.11  229160.95
11  0.0  1.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  0.0  1.0   91749.16  1

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split (x,y,test_size = 0.2,random_state= 42)
print ('X Shape-',x.shape)
print ('Y Shape-', y.shape)
print ('X_Train Shape-',x_train.shape)
print ('Y_Train Shape-',y_train.shape)
print ('X_Test Shape-',x_test.shape)
print ('Y_Test Shape-',y_test.shape)

X Shape- (50, 6)
Y Shape- (50,)
X_Train Shape- (40, 6)
Y_Train Shape- (40,)
X_Test Shape- (10, 6)
Y_Test Shape- (10,)


In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred= lr.predict(x_test)
print (y_pred)

[125685.70020548  84338.92317127  99390.93658774  46818.58913869
 128971.45588833  52062.29882128 109174.11382466  99985.2596175
  97162.65075527 115228.18387689]


In [14]:
result = pd.concat([pd.DataFrame(y_pred, columns = ['Prediction']),
                    pd.DataFrame(y_test,columns = ['Y_Test'])], axis =1)
result['Difference']= y_test -y_pred
print (result)

      Prediction     Y_Test    Difference
0  125685.700205  134307.35   8621.649795
1   84338.923171   81005.76  -3333.163171
2   99390.936588   99937.59    546.653412
3   46818.589139   64926.08  18107.490861
4  128971.455888  125370.37  -3601.085888
5   52062.298821   35673.41 -16388.888821
6  109174.113825  105733.54  -3440.573825
7   99985.259617  107404.34   7419.080383
8   97162.650755   97427.84    265.189245
9  115228.183877  122776.86   7548.676123


In [15]:
y_pre= pd.DataFrame(y_pred, columns =['Prediction'])
y_te = pd.DataFrame(y_test,columns= ['Actual'])
x_te = pd.DataFrame(x_test,columns= ['CF','FR','New Y','R&D','Admin','Mark'])
result = pd.concat([x_te,y_te,y_pre], axis =1)
result['Difference'] = y_pre ['Prediction']-y_te['Actual']
display (result)

CF   FR New Y       R&D      Admin       Mark     Actual     Prediction  \
0  1.0  0.0   0.0  91992.39  135495.07  252664.93  134307.35  125685.700205   
1  1.0  0.0   0.0  38558.51   82982.09   174999.3   81005.76   84338.923171   
2  0.0  0.0   1.0  61994.48  115641.28   91131.24   99937.59   99390.936588   
3  0.0  0.0   1.0   1000.23  124153.04    1903.93   64926.08   46818.589139   
4  0.0  0.0   1.0  94657.16  145077.58  282574.31  125370.37  128971.455888   
5  0.0  0.0   1.0    542.05   51743.15        0.0   35673.41   52062.298821   
6  0.0  0.0   1.0  75328.87  144135.98  134050.07  105733.54  109174.113825   
7  1.0  0.0   0.0  64664.71  139553.16  137962.62  107404.34   99985.259617   
8  1.0  0.0   0.0  63408.86  129219.61   46085.25   97427.84   97162.650755   
9  0.0  1.0   0.0   86419.7  153514.11        0.0  122776.86  115228.183877   

     Difference  
0  -8621.649795  
1   3333.163171  
2   -546.653412  
3 -18107.490861  
4   3601.085888  
5  16388.888821  
6   3440.573825  
7  -7419.080383  
8   -265.189245  
9  -7548.676123

In [16]:
accuracy = r2_score(y_test, y_pred)
print (accuracy)

0.8988481687286118


In [17]:
result = pd.concat([pd.DataFrame(y_pred, columns = ['Prediction']),
                    pd.DataFrame(y_test,columns = ['Y_Test'])], axis =1)
result['Difference']= y_test -y_pred
print (result)

      Prediction     Y_Test    Difference
0  125685.700205  134307.35   8621.649795
1   84338.923171   81005.76  -3333.163171
2   99390.936588   99937.59    546.653412
3   46818.589139   64926.08  18107.490861
4  128971.455888  125370.37  -3601.085888
5   52062.298821   35673.41 -16388.888821
6  109174.113825  105733.54  -3440.573825
7   99985.259617  107404.34   7419.080383
8   97162.650755   97427.84    265.189245
9  115228.183877  122776.86   7548.676123


In [18]:
pd.DataFrame(result).to_excel('MLR_Result.xlsx')

ModuleNotFoundError: No module named 'openpyxl'

In [ ]:
y_pre= pd.DataFrame(y_pred, columns =['Prediction'])
y_te = pd.DataFrame(y_test,columns= ['Actual'])
x_te = pd.DataFrame(x_test,columns= ['CF','FR','New Y','R&D','Admin','Mark'])
result = pd.concat([x_te,y_te,y_pre], axis =1)
result['Difference'] = y_pre ['Prediction']-y_te['Actual']
display (result)

CF   FR New Y       R&D      Admin       Mark     Actual     Prediction  \
0  1.0  0.0   0.0  91992.39  135495.07  252664.93  134307.35  125685.700205   
1  1.0  0.0   0.0  38558.51   82982.09   174999.3   81005.76   84338.923171   
2  0.0  0.0   1.0  61994.48  115641.28   91131.24   99937.59   99390.936588   
3  0.0  0.0   1.0   1000.23  124153.04    1903.93   64926.08   46818.589139   
4  0.0  0.0   1.0  94657.16  145077.58  282574.31  125370.37  128971.455888   
5  0.0  0.0   1.0    542.05   51743.15        0.0   35673.41   52062.298821   
6  0.0  0.0   1.0  75328.87  144135.98  134050.07  105733.54  109174.113825   
7  1.0  0.0   0.0  64664.71  139553.16  137962.62  107404.34   99985.259617   
8  1.0  0.0   0.0  63408.86  129219.61   46085.25   97427.84   97162.650755   
9  0.0  1.0   0.0   86419.7  153514.11        0.0  122776.86  115228.183877   

     Difference  
0  -8621.649795  
1   3333.163171  
2   -546.653412  
3 -18107.490861  
4   3601.085888  
5  16388.888821  
6   3440.573825  
7  -7419.080383  
8   -265.189245  
9  -7548.676123

In [ ]:
# y = mx+c
# y = m1x1+m2x2+m3x3+m4x4+m5x5+m6x6+C
lr.coef_

array([-1.22767929e+03,  1.42750258e+03, -1.99823287e+02,  8.09359318e-01,
       -7.82867439e-02,  2.84635373e-02])

In [ ]:
lr.intercept_

55874.21162482136

In [ ]:
result

CF   FR New Y       R&D      Admin       Mark     Actual     Prediction  \
0  1.0  0.0   0.0  91992.39  135495.07  252664.93  134307.35  125685.700205   
1  1.0  0.0   0.0  38558.51   82982.09   174999.3   81005.76   84338.923171   
2  0.0  0.0   1.0  61994.48  115641.28   91131.24   99937.59   99390.936588   
3  0.0  0.0   1.0   1000.23  124153.04    1903.93   64926.08   46818.589139   
4  0.0  0.0   1.0  94657.16  145077.58  282574.31  125370.37  128971.455888   
5  0.0  0.0   1.0    542.05   51743.15        0.0   35673.41   52062.298821   
6  0.0  0.0   1.0  75328.87  144135.98  134050.07  105733.54  109174.113825   
7  1.0  0.0   0.0  64664.71  139553.16  137962.62  107404.34   99985.259617   
8  1.0  0.0   0.0  63408.86  129219.61   46085.25   97427.84   97162.650755   
9  0.0  1.0   0.0   86419.7  153514.11        0.0  122776.86  115228.183877   

     Difference  
0  -8621.649795  
1   3333.163171  
2   -546.653412  
3 -18107.490861  
4   3601.085888  
5  16388.888821  
6   3440.573825  
7  -7419.080383  
8   -265.189245  
9  -7548.676123

In [ ]:
-1.22767929e+03*1+8.09359318e-01*91992.39+ -7.82867439e-02*135495.07+ 2.84635373e-02*252664.93+lr.intercept_

125685.7001810657

In [ ]:
y_fpred= lr.predict(x)
print (y_fpred)

[192212.6654547  187030.55971065 185183.93437003 174140.32762985
 172930.11655403 164924.33544173 155710.36151197 158957.99543859
 150463.49430464 154641.48410323 134995.5117714  138704.12846331
 127759.84928263 125685.70020548 149424.5704584  146216.94359658
 115791.91754095 128971.45588833 129388.42927957 115228.18387686
 115950.05160436 115612.79873554 113555.99633348 109700.5070828
 114259.51926276  99985.25961749 109174.11382465 114078.10758205
  99825.31692069  99841.95049279  99390.93658772  95712.15395368
  97162.65075525  98630.16447031  88531.79037816  92107.93605122
  74651.63335332  91908.32121706  72157.84688139  84338.92317127
  76212.09086728  75271.61487554  70462.80150005  59263.17807138
  61283.53057798  46818.58913867  57756.44854215  44044.39972196
  52062.29882126  46774.03661179]


In [ ]:
y_fpred= pd.DataFrame(y_fpred, columns =['Prediction'])
result = pd.concat([df1,y_fpred], axis =1)
result['Difference'] = result['Profit'] - result ['Prediction']
display (result)

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42  California  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68    New York  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95  California  146121.95   
11  100671.96        91790.61        249744.55     Florida  144259.40   
12   93863.75       127320.38        249839.44  California  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57    New York  124266.90   
19   86419.70       153514.11             0.00     Florida  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26  California  110352.25   
23   67532.53       105751.03        304768.73  California  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07    New York  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24    New York   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81    New York   96778.92   
34   46426.07       157693.92        210797.67     Florida   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82    New York   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67     Florida   78239.91   
41   27892.92        84710.77        164470.71  California   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

       Prediction    Difference  
0   192212.665455     49.164545  
1   187030.559711   4761.500289  
2   185183.934370   5866.455630  
3   174140.327630   8761.662370  
4   172930.116554  -6742.176554  
5   164924.335442  -7933.215442  
6   155710.361512    412.148488  
7   1589

In [ ]:
accuracy = r2_score(y, y_fpred)
print (accuracy)

0.9499635752382253


In [ ]:
print(x.dtype)

object


In [ ]:
x=x.astype('float64')

In [ ]:
print(x.dtype)

float64


In [ ]:
#recap below material later

In [ ]:
import statsmodels.api as sm
reg_ols = sm.OLS(endog = y, exog = x) #ordinary least square model is a type of linear least square method for estimating unknown paramteres in a linear regression model
#endog means dependant vaeiable, exog means independant variable
reg_ols = reg_ols.fit()
print(reg_ols.summary()) #prints summary of regressionr results

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     171.2
Date:                Wed, 10 Apr 2024   Prob (F-statistic):           1.14e-27
Time:                        21:20:55   Log-Likelihood:                -525.19
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          5.062e+04   6806.869      7.436      0.0

In [ ]:
# if p value is more than 0.5, then it will negatively affect model. P = 0 is ideal
#rows with above 0.5 values are removed
#R squared gives accuracy
x_opt = x[:,[0,1,2,3,5]]
import statsmodels.api as sm
reg_ols = sm.OLS(endog = y, exog = x_opt)
reg_ols = reg_ols.fit()
print(reg_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     216.9
Date:                Wed, 10 Apr 2024   Prob (F-statistic):           8.77e-29
Time:                        23:02:01   Log-Likelihood:                -525.42
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          4.681e+04   3130.528     14.954      0.0

In [ ]:
x_opt = x[:,[0,1,2,3]] #removing unnecessary columns
import statsmodels.api as sm
reg_ols = sm.OLS(endog = y, exog = x_opt)
reg_ols = reg_ols.fit()
print(reg_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.7
Date:                Wed, 10 Apr 2024   Prob (F-statistic):           2.70e-29
Time:                        23:05:32   Log-Likelihood:                -527.33
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           4.88e+04   3029.803     16.108      0.0

In [ ]:
pd.DataFrame(x_opt)

0    1    2          3
0   0.0  0.0  1.0  165349.20
1   1.0  0.0  0.0  162597.70
2   0.0  1.0  0.0  153441.51
3   0.0  0.0  1.0  144372.41
4   1.0  0.0  0.0  142107.34
5   0.0  0.0  1.0  131876.90
6   1.0  0.0  0.0  134615.46
7   0.0  0.0  1.0  130298.13
8   0.0  0.0  1.0  120542.52
9   1.0  0.0  0.0  123334.88
10  1.0  0.0  0.0  101913.08
11  0.0  1.0  0.0  100671.96
12  1.0  0.0  0.0   93863.75
13  1.0  0.0  0.0   91992.39
14  0.0  1.0  0.0  119943.24
15  0.0  0.0  1.0  114523.61
16  1.0  0.0  0.0   78013.11
17  0.0  0.0  1.0   94657.16
18  0.0  0.0  1.0   91749.16
19  0.0  1.0  0.0   86419.70
20  1.0  0.0  0.0   76253.86
21  0.0  0.0  1.0   78389.47
22  1.0  0.0  0.0   73994.56
23  1.0  0.0  0.0   67532.53
24  0.0  0.0  1.0   77044.01
25  1.0  0.0  0.0   64664.71
26  0.0  0.0  1.0   75328.87
27  0.0  0.0  1.0   72107.60
28  0.0  1.0  0.0   66051.52
29  0.0  0.0  1.0   65605.48
30  0.0  0.0  1.0   61994.48
31  0.0  0.0  1.0   61136.38
32  1.0  0.0  0.0   63408.86
33  0.0  0.0  1.0   55493.95
34  0.0  1.0  0.0   46426.07
35  0.0  0.0  1.0   46014.02
36  0.0  0.0  1.0   28663.76
37  1.0  0.0  0.0   44069.95
38  0.0  0.0  1.0   20229.59
39  1.0  0.0  0.0   38558.51
40  0.0  1.0  0.0   28754.33
41  1.0  0.0  0.0   27892.92
42  1.0  0.0  0.0   23640.93
43  0.0  0.0  1.0   15505.73
44  1.0  0.0  0.0   22177.74
45  0.0  0.0  1.0    1000.23
46  0.0  1.0  0.0    1315.46
47  1.0  0.0  0.0       0.00
48  0.0  0.0  1.0     542.05
49  1.0  0.0  0.0       0.00

In [ ]:
#creating model with only administration spent column
x_opt = x[:,[4]]
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x_opt)
reg_ols = reg_ols.fit()
print(reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.871
Model:                            OLS   Adj. R-squared (uncentered):              0.868
Method:                 Least Squares   F-statistic:                              331.2
Date:                Wed, 10 Apr 2024   Prob (F-statistic):                    1.92e-23
Time:                        23:10:39   Log-Likelihood:                         -604.03
No. Observations:                  50   AIC:                                      1210.
Df Residuals:                      49   BIC:                                      1212.
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [ ]:
x_opt = x[:,[3]]
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
xopt_train,xopt_test,y_train,y_test =train_test_split (x_opt,y,test_size = 0.2,random_state= 42)
print (x_opt.shape)
print ( y.shape)
print (xopt_train.shape)
print (xopt_test.shape)
print (y_train.shape)
print (y_test.shape)

(50, 1)
(50,)
(40, 1)
(10, 1)
(40,)
(10,)


In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(xopt_train, y_train)
print(reg)

LinearRegression()


In [ ]:
yopt_pred = reg.predict(xopt_test)
print(yopt_pred)

[127862.20996405  82250.56334619 102255.72078164  50190.4734756
 130136.88190548  49799.36685472 113638.0775288  104535.0534288
 103463.04843113 123105.31102669]


In [ ]:
result = pd.concat([pd.DataFrame(yopt_pred, columns =['Prediction']),
                    pd.DataFrame(y_test,columns = ['Y_Test'])], axis =1)
result['Difference']= result['Y_Test'] - result ['Prediction']
print (result)

      Prediction     Y_Test    Difference
0  127862.209964  134307.35   6445.140036
1   82250.563346   81005.76  -1244.803346
2  102255.720782   99937.59  -2318.130782
3   50190.473476   64926.08  14735.606524
4  130136.881905  125370.37  -4766.511905
5   49799.366855   35673.41 -14125.956855
6  113638.077529  105733.54  -7904.537529
7  104535.053429  107404.34   2869.286571
8  103463.048431   97427.84  -6035.208431
9  123105.311027  122776.86   -328.451027


In [ ]:
accuracy = r2_score(y_test, yopt_pred)
print (accuracy)

0.9265108109341951


In [ ]:
yfull_pred= reg.predict(x_opt)
print (yfull_pred)

[190480.25107829 188131.54561896 180315.73844483 172574.27208786
 170640.7877067  161907.99094882 164245.6507063  160560.33849815
 152232.86095279 154616.44488025 136330.60130088 135271.16996536
 129459.61990349 127862.20996405 151721.31008683 147095.06455947
 115929.36923955 130136.88190548 127654.58662083 123105.31102669
 114427.65741716 116250.63356326 112499.09836055 106983.05069951
 115102.13665346 104535.0534288  113638.0775288  110888.37211903
 105718.84707519 105338.10326888 102255.72078164 101523.23880648
 103463.04843113  96706.80916997  88966.38421611  88614.65458336
  73804.31462961  86955.17872572  66604.83030328  82250.56334619
  73881.62600648  73146.31858518  69516.78119611  62572.50038466
  68267.78888609  50190.4734756   50459.55667456  49336.66803799
  49799.36685472  49336.66803799]


In [ ]:
accuracy = r2_score(y, yfull_pred)
print (accuracy)#model shows improved results from before

0.9464943582068932


In [ ]:
df_Predict = pd.read_csv('50_Startups_Predictions.csv')
print (df_Predict)

    R&D Spend  Administration  Marketing Spend       State
0   120542.52       148718.95        311613.29    New York
1   123334.88       108679.17        304981.62  California
2   101913.08       110594.11        229160.95  California
3   100671.96        91790.61        249744.55     Florida
4    93863.75       127320.38        249839.44  California
5    91992.39       135495.07        252664.93  California
6   119943.24       156547.42        256512.92     Florida
7   114523.61       122616.84        261776.23    New York
8    78013.11       121597.55        264346.06  California
9    72107.60       127864.55        353183.81    New York
10   66051.52       182645.56        118148.20     Florida
11   65605.48       153032.06        107138.38    New York
12   61994.48       115641.28         91131.24    New York
13   61136.38       152701.92         88218.23    New York
14   63408.86       129219.61         46085.25  California
15   55493.95       103057.49        214634.81    New Yo

In [ ]:
print(df_Predict.count())

R&D Spend          28
Administration     28
Marketing Spend    28
State              28
dtype: int64


In [ ]:
x_Predict = df_Predict.iloc[:,0:1].values
print (x_Predict)

[[120542.52]
 [123334.88]
 [101913.08]
 [100671.96]
 [ 93863.75]
 [ 91992.39]
 [119943.24]
 [114523.61]
 [ 78013.11]
 [ 72107.6 ]
 [ 66051.52]
 [ 65605.48]
 [ 61994.48]
 [ 61136.38]
 [ 63408.86]
 [ 55493.95]
 [ 46426.07]
 [ 46014.02]
 [ 28663.76]
 [ 44069.95]
 [ 20229.59]
 [ 38558.51]
 [ 22177.74]
 [  1000.23]
 [  1315.46]
 [     0.  ]
 [   542.05]
 [     0.  ]]


In [ ]:
print (pd.DataFrame(x_Predict))

            0
0   120542.52
1   123334.88
2   101913.08
3   100671.96
4    93863.75
5    91992.39
6   119943.24
7   114523.61
8    78013.11
9    72107.60
10   66051.52
11   65605.48
12   61994.48
13   61136.38
14   63408.86
15   55493.95
16   46426.07
17   46014.02
18   28663.76
19   44069.95
20   20229.59
21   38558.51
22   22177.74
23    1000.23
24    1315.46
25       0.00
26     542.05
27       0.00


In [ ]:
yone_Predict = reg.predict(x_Predict)
print(yone_Predict)

[152232.86095279 154616.44488025 136330.60130088 135271.16996536
 129459.61990349 127862.20996405 151721.31008683 147095.06455947
 115929.36923955 110888.37211903 105718.84707519 105338.10326888
 102255.72078164 101523.23880648 103463.04843113  96706.80916997
  88966.38421611  88614.65458336  73804.31462961  86955.17872572
  66604.83030328  82250.56334619  68267.78888609  50190.4734756
  50459.55667456  49336.66803799  49799.36685472  49336.66803799]


In [ ]:
yone_Predict= pd.DataFrame(yone_Predict, columns =['Prediction'])
result = pd.concat([df_Predict,yone_Predict], axis =1)
result.to_excel('Regressions_future.xlsx')
print (result)

    R&D Spend  Administration  Marketing Spend       State     Prediction
0   120542.52       148718.95        311613.29    New York  152232.860953
1   123334.88       108679.17        304981.62  California  154616.444880
2   101913.08       110594.11        229160.95  California  136330.601301
3   100671.96        91790.61        249744.55     Florida  135271.169965
4    93863.75       127320.38        249839.44  California  129459.619903
5    91992.39       135495.07        252664.93  California  127862.209964
6   119943.24       156547.42        256512.92     Florida  151721.310087
7   114523.61       122616.84        261776.23    New York  147095.064559
8    78013.11       121597.55        264346.06  California  115929.369240
9    72107.60       127864.55        353183.81    New York  110888.372119
10   66051.52       182645.56        118148.20     Florida  105718.847075
11   65605.48       153032.06        107138.38    New York  105338.103269
12   61994.48       115641.28         