In [2]:
import numpy as np

In [12]:
a = np.array([[10,11,12],[20,21,22]])
print (a)

[[10 11 12]
 [20 21 22]]


In [14]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
b = np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
mat1 = np.arange(0,30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
mat1 = np.arange(30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
mat2 = np.reshape (mat1, (6,5), 'F') #f means values are generated column wise
print(mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [21]:
mat2 = np.reshape (mat1, (6,5), 'C') #c means values generated row wise
print(mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [22]:
mat2 = np.reshape (mat1, (2,5,3), 'F')
print(mat2)

[[[ 0 10 20]
  [ 2 12 22]
  [ 4 14 24]
  [ 6 16 26]
  [ 8 18 28]]

 [[ 1 11 21]
  [ 3 13 23]
  [ 5 15 25]
  [ 7 17 27]
  [ 9 19 29]]]


In [23]:
mat2 = np.reshape (mat1, (2,5,3), 'c')
print(mat2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [24]:
#transpose of matrix below
print (mat1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [25]:
m5 = mat1.reshape(6,5)
m5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [26]:
m5.T #transpose here

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [28]:
#arithmatic operations
a = np.arange(9) #first 9.. 0 to 8
b = a.reshape (3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
a = np.arange(2,11) #from 2 to 10
c = a.reshape (3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
#addition
print (b)
print () #prints gaps
print (c)
print ()
b+c

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
#subtraction
c-b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [37]:
#multiplication element-wise(mathematically incorrect)
b*c

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [38]:
b@c #proper matrix multiplication done using @ symbol

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [39]:
b/c #division

array([[0.        , 0.33333333, 0.5       ],
       [0.6       , 0.66666667, 0.71428571],
       [0.75      , 0.77777778, 0.8       ]])

In [137]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
add = var1 + var2
print(add)

[2 4 6 8]


In [40]:
b%c #remainder

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
b//c #floor division

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
c//b

/var/folders/w1/c2vvrx9d61j9dv7jwtkkdg900000gn/T/ipykernel_1444/3639078968.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  c//b


array([[0, 3, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [138]:
#power
var1 = np.array([1,2,3,4])
pow = np.power(var1,3)
print(pow)

[ 1  8 27 64]


In [139]:
#reciprocal
var1 = np.array([1,2,3,4])
reci = np.reciprocal(var1)
reci

array([1, 0, 0, 0])

In [44]:
mat2 #3d array
print()
print (mat2.ravel()) #converts directly to 1d array instead of using reshape


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [48]:
#splitting an array equally
vector = np.linspace(20,40,7) #(starting value, ending value, interval
print (vector) #gives the equaly divided values

[20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.        ]


In [49]:
#dictionary
EU_Sales = [1002, 4523, 4123, 3584]
APAC_Sales = [7854, 9654, 4582, 8543]
US_Sales = [7845, 4512, 3652, 7452]
Sales = np.array([EU_Sales, APAC_Sales, US_Sales])
print (Sales)

[[1002 4523 4123 3584]
 [7854 9654 4582 8543]
 [7845 4512 3652 7452]]


In [50]:
Sales[1] #specific row

array([7854, 9654, 4582, 8543])

In [51]:
Sales[1][2] #specifc index in a row

4582

In [54]:
#get value based on input region name: dictionary
R = {'EU':0, 'APAC':1, 'US':2} #key value pairs
R

{'EU': 0, 'APAC': 1, 'US': 2}

In [55]:
Q = {'Q1':0, 'Q2':1, 'Q3':2, 'Q4':3} #column relation
Q

{'Q1': 0, 'Q2': 1, 'Q3': 2, 'Q4': 3}

In [62]:
R['APAC']
print()
Sales[R['APAC'],Q['Q3']]

4582

In [63]:
#slicing
arr1 = np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
arr1 = np.arange(200,300)
arr1

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299])

In [67]:
print(arr1[10:],'\n') #all values from index 10

[210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227
 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245
 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263
 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281
 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299] 



In [73]:
print(arr1[10:20])

[210 211 212 213 214 215 216 217 218 219]


In [70]:
print(arr1[10:50:5])

[210 215 220 225 230 235 240 245]


In [72]:
print(arr1[50:10:-5])

[250 245 240 235 230 225 220 215]


In [76]:
arr1 = np.arange(20)
print (arr1)
arr_slice = slice(1,10,2)
print(arr_slice,'\n')
print(arr1[arr_slice])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(1, 10, 2) 

[1 3 5 7 9]


In [78]:
arr1 = np.arange(9)
print(arr1)
arr1 = arr1.reshape(3,3)
print('\n')
print(arr1)

[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
#to get only this:
4 5 #a22, a23
7 8 #a32, a33

In [81]:
arr1[1:3,1:3] #[starting row: ending row , starting column:ending column]

array([[4, 5],
       [7, 8]])

In [82]:
#array operations
print(arr1.shape) #shape in (no. of rows, no. of columns)

(3, 3)


In [83]:
print(arr1.ndim) #shows dimension of array

2


In [84]:
print(arr1.itemsize) #size of each element in bytes
print(arr1.dtype) #data type

8
int64


In [85]:
print(arr1.size) #no. of elements

9


In [86]:
print(arr1.min())

0


In [87]:
print(arr1.max())

8


In [88]:
print(arr1.sum())

36


In [89]:
print(np.sqrt(arr1))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [90]:
print(np.std(arr1)) #standard deviation(shows how spread out the overall data is)

2.581988897471611


In [140]:
var = np.array([1,2,3]) #sin value
print(np.sin(var))

[0.84147098 0.90929743 0.14112001]


In [141]:
var = np.array([1,2,3]) #cos value
print(np.cos(var))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [142]:
#cumsum: fibonacci series
print(np.cumsum(var))

[1 3 6]


In [95]:
#empty array
arr5 = np.empty([3,2], dtype = float) #used to create array without initializing it's memory
print (arr5)

[[4.94e-323 5.43e-323]
 [5.93e-323 9.88e-323]
 [1.04e-322 1.09e-322]]


In [96]:
arr5 = np.empty([3,2], dtype = int)
print(arr5)

[[10 11]
 [12 20]
 [21 22]]


In [97]:
arr5 = np.empty([3,2], dtype = bool)
print(arr5)

[[ True  True]
 [ True  True]
 [ True  True]]


In [98]:
arr5 = np.empty([3,2], dtype = str)
print (arr5)

[['' '']
 ['' '']
 ['' '']]


In [99]:
#IMP: list of all nupy commands
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [100]:
arr1 = np.array([1,2,3], dtype = np.float64) #specify datatype while making array
arr1

array([1., 2., 3.])

In [101]:
arr1 = np.array([1,2,3], dtype = bool)
arr1

array([ True,  True,  True])

In [102]:
#converting datatype
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype,'\n')
float_arr = arr.astype(np.float64)
float_arr

[1 2 3 4 5]
int64 



array([1., 2., 3., 4., 5.])

In [103]:
#sorting array
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [104]:
arr = np.array(['banaba', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banaba' 'cherry']


In [109]:
arr = np.array([[3,2,4],[5,0,1]]) #row wise sorting is taken by fefault
print(np.sort(arr),'\n')
print(np.sort(arr, axis = 0),'\n') #column is taken due to axis = 0
print(np.sort(arr, axis = 1)) #axis = 1 means the default row wise sorting 

[[2 3 4]
 [0 1 5]] 

[[3 0 1]
 [5 2 4]] 

[[2 3 4]
 [0 1 5]]


In [111]:
#deleting
arr = np.arange(10,19)
print(arr)

[10 11 12 13 14 15 16 17 18]


In [112]:
arr = np.delete(arr, [2,5])
arr

array([10, 11, 13, 14, 16, 17, 18])

In [117]:
#deleting for 2d array
arr2 = np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [120]:
a = np.delete(arr2,1,0) #.delete(name of array, row number, axis)
print(a)

[[10 11 12 13]
 [18 19 20 21]]


In [122]:
a = np.delete(arr2,1,1) #axis = 1 now, so column deletion
a

array([[10, 12, 13],
       [14, 16, 17],
       [18, 20, 21]])

In [124]:
#user input
l = []

for i in range(1,5):
    int1 = int(input("Enter number:"))
    l.append(int1)
print(np.array(l))

Enter number: 2
Enter number: 3
Enter number: 4
Enter number: 5


[2 3 4 5]


In [126]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [127]:
#identity matrix
ar_dia = np.eye(3)
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
#rand() generates values between 0 and 1
var = np.random.rand(4)
var

array([0.42587991, 0.05640521, 0.20722983, 0.19521017])

In [129]:
var1 = np.random.rand(2,5)
var1

array([[0.07359378, 0.38199589, 0.27707101, 0.26504284, 0.98919126],
       [0.54497991, 0.16827633, 0.99137858, 0.88383748, 0.89669635]])

In [130]:
#randn() uses negative and possitive number both close to 0
var2 = np.random.randn(5)
print(var2)

[-1.47475612 -0.0872229   0.59352349  0.87458016 -0.77264588]


In [131]:
#ranf()returns arrays of specified shapes and fills it with random floats in half open interval
var3 = np.random.ranf(4)
var3

array([0.96262782, 0.05545814, 0.91906586, 0.00631086])

In [132]:
#randint is used to generate a random number in given range
var4 = np.random.randint(5,20,5) #randint(min,max,total value = total amount of values to be generated)
var4

array([ 7,  7, 12,  9,  9])

In [135]:
x = np.array([1,2,3,4])
new = np.float32(x)
new1 = np.int_(new)
print("Data Type:", x.dtype)
print("Data Type:", new.dtype)
print("Data Type:", new1.dtype)
print(x)
print(new)
print(new1)

Data Type: int64
Data Type: float32
Data Type: int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [136]:
#astype: changes type directly
x2 = np.array([1,2,3,4])
new = x2.astype(float)
print(x2)
print(new)

[1 2 3 4]
[1. 2. 3. 4.]


In [4]:
#adding 2 matrix of diff mXn
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


In [8]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [14]:
#copy
var = np.array([1,2,3,4])
co = var.copy() #makes a copy seperate from original copy
var[1]=40
print(var)
print(co)

[ 1 40  3  4]
[1 2 3 4]


In [15]:
x = np.array([9,8,7,6,5])
vi = x.view() #view will make a view of the og array, changing view changes og array
x[1]=40
print(x)
print(vi)

[ 9 40  7  6  5]
[ 9 40  7  6  5]


In [16]:
#concatination
var1 = np.array([1,2,3,4])
var2 = np.array([9,8,7,6])
ar = np.concatenate((var1,var2))
ar

array([1, 2, 3, 4, 9, 8, 7, 6])

In [21]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[9,8],[7,6]])
ar = np.concatenate((var1,var2),axis=1)
ar

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])

In [24]:
var_1 = np.array([[1,2],[3,4]])
var_2 = np.array([[9,8],[7,6]])
arr = np.stack((var_1,var_2),axis=1)
arr

array([[[1, 2],
        [9, 8]],

       [[3, 4],
        [7, 6]]])

In [20]:
#splitting array
var = np.array([1,2,3,4,5,6])
split = np.array_split(var,3) #np.array_split(name of array, no. of arrays to be formed)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
#searching

var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where(var == 2) #stores the index number for the variable being searched
print(x)

(array([1, 4, 6]),)


In [29]:
var = np.array([4,2,3,4,2,5,2,6,7])
x = np.where((var%2) == 0)
x

(array([0, 1, 3, 4, 6, 7]),)

In [33]:
#search sorted array
var1 = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(var1,5,side = 'right') #side = sets from which side search happens
x

4

In [36]:
var = np.array(['a','s','d','f'])
f = [True,False,False,True] #onlythose matching will be printed
a = var[f]
a

array(['a', 'f'], dtype='<U1')

In [38]:
#shuffling
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
var

array([2, 4, 3, 5, 1])

In [39]:
#unique gives a unique data from repetation
var = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var)
x

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
var = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var)
x

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
#resize: changes size of array
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3)) #np.resize(var, (row, cloumn))
y


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3)) 
print(y.flatten()) #makes into 1d

[1 2 3 4 5 6]


In [48]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3)) 
print(y.flatten(order = 'F')) #places F order

[1 4 2 5 3 6]


In [50]:
#inserting value
var = np.array([1,2,3,4,])
print(var)
v = np.insert(var,2,40) #np.insert(array name, index number, value)
v

[1 2 3 4]


array([ 1,  2, 40,  3,  4])

In [52]:
var = np.array([1,2,3,4,])
print(var)
v = np.insert(var,(2,4),40) #inserting in multiple places
v

[1 2 3 4]


array([ 1,  2, 40,  3,  4, 40])

In [55]:
#appending
var = np.array([1,2,3,4,])
print(var)
x = np.append(var,6.5) #np.append(array, value, axis(1 takden default))

[1 2 3 4]


In [62]:
var = np.array([[1,2,3],[1,2,3]])
x = np.append(var, [[45,44,23]],axis = 0)
x

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [45, 44, 23]])

In [64]:
#deleting
var = np.array([1,2,3,4])
delete = np.delete(var,2)
delete

array([1, 2, 4])

In [66]:
#matrix
var = np.matrix([[1,2,3],[1,2,3]])
var

matrix([[1, 2, 3],
        [1, 2, 3]])

In [67]:
var = np.matrix([[1,2,3],[1,2,3]])
print(np.transpose(var))

[[1 1]
 [2 2]
 [3 3]]


In [68]:
var = np.matrix([[1,2,3],[1,2,3]])
print(np.swapaxes(var,0,1))

[[1 1]
 [2 2]
 [3 3]]


In [71]:
var = np.matrix([[1,2,],[3,5]])
print(np.linalg.inv(var)) #inverse matrix

[[-5.  2.]
 [ 3. -1.]]


In [73]:
var = np.matrix([[1,2,],[3,5]])
print(np.linalg.matrix_power(var,3))

[[ 43  74]
 [111 191]]


In [74]:
var = np.matrix([[1,2,],[3,5]])
print(np.linalg.det(var))

-1.0000000000000004
